version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 80
    container_name: dnd-app
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./:/app
    networks:
      - dnd-network

  db:
    image: mysql:5.7.22
    container_name: dnd-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dnd
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - dnd-network

networks:
  dnd-network:
    driver: bridge

volumes:
  dbdata:
    driver: local